{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nestjs.fullname" . }}-web
  labels:
    {{- include "nestjs.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "nestjs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
{{- end }}
